<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_WebForms TreeView Overview_rtPlus rtPlusHover</name>
   <tag></tag>
   <elementGuidId>345fa0aa-ffe3-4c48-b34e-851e127a5d55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.rtPlus.rtPlusHover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_ContentPlaceholder1_RadTreeView1']/ul/li/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6cf6a98e-09d1-4217-934c-2657e970fe1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rtPlus rtPlusHover</value>
      <webElementGuid>f1bd1dd0-920a-4a42-9bd3-e2ba5b8a6510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceholder1_RadTreeView1&quot;)/ul[@class=&quot;rtUL rtLines&quot;]/li[@class=&quot;rtLI rtFirst rtLast&quot;]/div[@class=&quot;rtOut&quot;]/span[@class=&quot;rtPlus rtPlusHover&quot;]</value>
      <webElementGuid>96370ab0-d0c8-4838-86cb-f29efebd57bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceholder1_RadTreeView1']/ul/li/div/span</value>
      <webElementGuid>ad6e9227-bafa-46e7-9ecc-830fc639b830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/ul/li/div/span</value>
      <webElementGuid>9ab463d3-2c7b-495a-8571-da1b1e2d99a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
