<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_AppliTools Artificial Intelligences App_7a5097</name>
   <tag></tag>
   <elementGuidId>fcde18ed-0af0-496d-9b14-02c06e74c0e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.alignnone.size-full.wp-image-1816</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='node-292']/div/div/div/div/div[11]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>249d2aa3-0543-4c6a-913e-d2a902546f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alignnone size-full wp-image-1816</value>
      <webElementGuid>ccbd4514-b248-4cf6-b88e-3af050d66539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://testautomationresources.com/wp-content/uploads/2020/09/applitools-and-perfecto-221.png</value>
      <webElementGuid>27b527f5-6397-4f44-969d-baf699a889a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>AppliTools</value>
      <webElementGuid>6ece31ea-ee83-42ad-b5d0-ddf48cc90d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>850px</value>
      <webElementGuid>32f3fc7a-61e4-4b4a-9284-791a08917b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>225px</value>
      <webElementGuid>08c7d7ae-41da-4c99-8733-f8c9c6ee5df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;node-292&quot;)/div[@class=&quot;field field-name-body field-type-text-with-summary field-label-hidden&quot;]/div[@class=&quot;field-items&quot;]/div[@class=&quot;field-item even&quot;]/div[1]/div[11]/img[@class=&quot;alignnone size-full wp-image-1816&quot;]</value>
      <webElementGuid>945de484-76b8-43f8-9e3b-7d8c8070570e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='node-292']/div/div/div/div/div[11]/img</value>
      <webElementGuid>b830ee6c-424f-45bb-ac8a-d55bcbc1680e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='AppliTools']</value>
      <webElementGuid>cc5756d4-7511-4393-9f2e-cad19e2c6c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/img</value>
      <webElementGuid>12ff1ee8-e69b-43fb-a3b5-7eaed466b9e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://testautomationresources.com/wp-content/uploads/2020/09/applitools-and-perfecto-221.png' and @alt = 'AppliTools']</value>
      <webElementGuid>22700642-910e-4668-893a-0edd57a95f31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
