<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Año</name>
   <tag></tag>
   <elementGuidId>98ca4f0a-ff95-4f21-a339-0fa02375e921</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@class,'month-select')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[class=&quot;react-datepicker__year-select&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
