<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Mes</name>
   <tag></tag>
   <elementGuidId>669fde65-4e0e-4170-9335-cff25262bb20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>select[class='react-datepicker__month-select']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[class='react-datepicker__month-select']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
