<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sports</name>
   <tag></tag>
   <elementGuidId>0d579967-4e3c-42e5-bb14-fc699db8d1cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[contains(text(),'Sports')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[id=&quot;hobbies-checkbox-1&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
