<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Permanent Address_permanentAddress</name>
   <tag></tag>
   <elementGuidId>2f0096fd-2153-4fc9-b05f-34cbba642ddd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='permanentAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#permanentAddress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3770f7d8-975c-4287-8273-69ccae35c923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>427f326f-6c6d-4229-9ab7-0c433fa2182f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>5a47b961-b278-47df-90e5-40948362e4f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>permanentAddress</value>
      <webElementGuid>a6a54042-8be4-48b4-b73f-f2dd7d583ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ca8791dd-4855-4c49-913e-874d54a8c966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;permanentAddress&quot;)</value>
      <webElementGuid>7529d204-3e01-41f1-bfc7-77bebeb98106</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='permanentAddress']</value>
      <webElementGuid>3e6bec30-7aac-4deb-acb5-cc81c5f94b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='permanentAddress-wrapper']/div[2]/textarea</value>
      <webElementGuid>a598fce3-d24d-42d3-8820-2cda234b238d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/textarea</value>
      <webElementGuid>21818e02-14b3-4c8a-b38b-f0fc11c803fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'permanentAddress']</value>
      <webElementGuid>2ceb412f-c1aa-4108-893e-86c943fc2fe9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
