<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_NamealejandroEmailcanosa1msn.comCurrent_59e2b2</name>
   <tag></tag>
   <elementGuidId>a69e114e-ac8d-4180-b985-92749c8a7073</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='output']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.border.col-md-12.col-sm-12</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>94163988-15da-43f4-bb6c-8cc56ab3f626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border col-md-12 col-sm-12</value>
      <webElementGuid>ff9f6ab0-a674-4998-98a5-09b7751a3535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Name:alejandroEmail:canosa1@msn.comCurrent Address :calle doctor esquerdo 56 Permananet Address :calle doctor esquerdo 67</value>
      <webElementGuid>cee7e615-afd4-43ff-9b2a-829a74b9c643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;output&quot;)/div[@class=&quot;border col-md-12 col-sm-12&quot;]</value>
      <webElementGuid>a50457de-484c-42ff-b8f4-918d799036aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='output']/div</value>
      <webElementGuid>b601e393-44c6-4eba-b7f7-3dc1553a01d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::div[2]</value>
      <webElementGuid>f07432ec-ee90-4022-a66f-e3c451cad6db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permanent Address'])[1]/following::div[5]</value>
      <webElementGuid>89406ba2-dd82-40bf-8185-df48425e1d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2013-2020 TOOLSQA.COM | ALL RIGHTS RESERVED.'])[1]/preceding::div[8]</value>
      <webElementGuid>1c14647f-708c-47a6-90c1-337fae4805c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'output', '&quot;', ')/div[@class=', '&quot;', 'border col-md-12 col-sm-12', '&quot;', ']')])[1]/preceding::div[9]</value>
      <webElementGuid>cd28463e-57c7-472f-b490-955e6ef5df85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[6]/div</value>
      <webElementGuid>deac49e9-5ac4-4c60-98ac-7a4af4fe763d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Name:alejandroEmail:canosa1@msn.comCurrent Address :calle doctor esquerdo 56 Permananet Address :calle doctor esquerdo 67' or . = 'Name:alejandroEmail:canosa1@msn.comCurrent Address :calle doctor esquerdo 56 Permananet Address :calle doctor esquerdo 67')]</value>
      <webElementGuid>919ab2d1-ac94-4778-9b6e-65568359170e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
